### ISSUE TITLE
Xamarin.Auth 1.3.1 fails compilation due to PCLCrypto dependency not found

### ISSUE THREAD

**Issue by lirkki** [xamarin/Xamarin.Auth#123]
Steps to reproduce:
1) Create a new Xamarin.Android app in Visual Studio
2) Add Xamarin.Auth dependency (version 1.3.1)
3) Compile the app

Expected result: The app can be compiled successfully.

Actual result: Compilation fails with this error

```
Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'PCLCrypto, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d4421c8a4786956c'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'PCLCrypto.dll'
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute() LifecareLasna.Droid     
```

**Comment by moljac** [comment]
Adding this dependency in 1.3.1.1 right now.

1.3.2-alpha-01 with some fixes for older bugs will be published prior to 1.3.1.1

**Comment by moljac** [comment]
1.3.1.1 published. Test it please and reportif issue persists.

If everything is OK. I'll kindly ask you to close thid issue.

**Comment by lirkki** [comment]
Cannot reproduce in 1.3.1.1 anymore. Thanks @moljac for quick action!

Just as a sidenote: PCLCrypto version that gets installed with 1.3.1.1 is 0.5.0.14108 which seems rather old (current latest version 2.0.147). It also installs version 2.0.4.14103 of Validation dependency which is not the latest (currently 2.3.7).

**Comment by moljac** [comment]
@lirkki No need to thank me. It is my duty to fix it ASAP.

OK. I did not specify dependency version in nuspec, so this is a bit odd. We'll check if nuget on Mac (and packaging) causes problems (again).

I did use 2.x

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/source/Xamarin.Auth.XamarinAndroid/packages.config#L7

And there is another odd thing - only Xamarin.Android was influenced by this problem (Xamarin.University team reported)

**Comment by adamhewitt627** [comment]
Trying to update iOS to this gives `Package Validation 2.0.4.14103 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Package Validation 2.0.4.14103 supports: portable-monoandroid+monotouch+net40+sl5+win8+wp8+wp81+wpa81 (.NETPortable,Version=v0.0,Profile=windows8+net40+sl5+wp8+wpa81+wp81+MonoAndroid+MonoTouch)`

Staying at 1.3.1 then fails a release build with the PCLCrypto dependency.

**Comment by moljac** [comment]
@adamhewitt627 Can you test 1.3.1.1 please and let me know if it was fixed.

@lirkki Can this issue be closed in your case?

**Comment by adamhewitt627** [comment]
I can't confirm until Tuesday when I'm back at work, but I know this much:

 - iOS won't update to 1.3.1.1 (gives the error message above)
 - iOS at 1.3.1 fails AOT in release build on PCLCrypto dependency

I think Android might've still failed AOT compile without including PCLCrypto myself (also did that as a workaround for iOS) but I don't remember for sure.

**Comment by moljac** [comment]
@adamhewitt627 No problems at all for confirmation.

Regarding update: seems like Xamarin10 (unified) support is not in that PCL Profile. Can I ask why are you using 2.0.4.14103?
From this one the latest version is 2.0.147?? I'm a bit confused.

https://www.nuget.org/packages/pclcrypto

**Comment by moljac** [comment]
@lirkki Is this issue solved for Android?

**Comment by lirkki** [comment]
@moljac Yes this is ok on Android :+1:

**Comment by moljac** [comment]
@adamhewitt627 Is this issue solved in your case?

**Comment by hvaughan3** [comment]
@moljac I am still getting the iOS error that adam talked about. I tried installing the latest Xamarin Auth nuget, got the error, updated PCLCrypto to the latest version which also update Validation. Then I was able to go back and install Xamarin Auth without errors.

Though I am not sure yet if updating PCLCrypto to the latest version will cause issues later on since some method signatures were changed in the latest versions of PCLCrypto. Working on testing everything now and will report back or edit this post if I run into issues.

For completeness these are the versions of libraries I now have installed:

PCLCrypto - 2.0.147
Validation - 2.2.8
Xamarin Auth - 1.3.1.1

**Comment by moljac** [comment]
@hvaughan3 
I'm confused, because I tried to reproduce this problem and cannot, because I do not need to update PCLCrypto package or any other (after iOS app creation). 

There is no version constraint on nuget package dependency:

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/nuget/Xamarin.Auth.nuspec#L83

So, nuget should grab the latest version and this should be:

https://www.nuget.org/packages/PCLCrypto
https://www.nuget.org/packages/PCLCrypto/2.0.147

And this is in Xamarin.Auth iOS too:

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/source/Xamarin.Auth.XamarinIOS/packages.config#L7

This seems like nuget problem. I currently work on using this Xamarin.Auth version in Xamarin.Social and some other packages/components and will try to reproduce this problem - if I can

**Comment by hvaughan3** [comment]
@moljac That is indeed weird. I do not know nearly enough about NuGet to be very helpful, unfortunately but please let me know if there is anything I can do to help.

**Comment by zengable** [comment]
I used to use the component store version of Xamarin.Auth without problems but since iOS 10 came out it cannot save accounts anymore. As the component store version is outdated I wanted to update via nuget but then the project did not compile anymore, I had PCLCrypto related issues as well:

MTOUCH: error MT2002: Failed to resolve "System.Byte[] PCLCrypto.ICryptographicBuffer::GenerateRandom(System.Int32)" reference from "PCLCrypto, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d4421c8a4786956c"

1. Xamarin.Auth can't be installed by default via nuget. I have to manually add the Validation nuget first.
2. PCLCrypto 0.5.0.14108 gets installed by default when I install Xamarin.Auth, this is causing the error stated above. So the PCLCrypto package has to be manually update as well.
3. Now the project compiles but I guess I need to open a separate issue ticket as the lib still can't save the Account

**Comment by milan-is-a-dick** [comment]
@rashidovich 

I got it working by first uninstalling Xamarin.Auth and then installing PCLCrypto 0.5.0.14108 for iOS and the general project, then I reinstalled Wamarin.Auth 1.3.1 for iOS and the general project. Once I set the entitlements.plist it worked :)

**Comment by Beej126** [comment]
in my case this error came from referencing the compiled DLL from "PCLProj" in an "iOSProj", where iOSProj was referencing a different version of PCLCrypto than PCLProj...  the **build error messages offered zero clues to this underlying issue*** from what i can see, even with full debug output enabled in VSTS.

it turns out i actually didn't actually need to reference PCLCrypto in iOSProj for now so i might've been able to stick with precompiled DLL reference... but given general preference to follow evolving package versions, and might wind up needing those libs directly in iOSProj, and forget about this hidden "sharp edge", i decided to go ahead and include full PCLProj code in iOSProj's solution.

after ironing that out, i was able to nuget reference latest versions of all dependencies solely in PCLProj - Xamarin.Auth v1.3.1.1, Validation v2.3.7 and PCLCrypto v2.0.147

i can also confirm even though it's a Xamarin Forms iOS/Android solution and latest PCLCrypto nuget pulls in several Windows'y looking nugets (PInvoke.Kernel32, PInvoke.Windows.Core, etc), the app runs fine on iOS... presumably they get dropped out accordingly through conditional linking or some such.

for the record, PCLProj in this case is "Auth0Client" from GitHub... they do have a prepackaged Xamarin Component (sortof a NuGet alternative) but it has old references to the aforementioned dependencies.

**Comment by moljac** [comment]
Solved in nuget version 1.3.2 

https://www.nuget.org/packages/Xamarin.Auth/1.3.2

Closing

**Comment by geraldons** [comment]
O erro Voltou. não implanta mais no Android.

**Comment by alicint** [comment]
still getting this error on the latest nuget version

**Comment by omarmallat** [comment]
I'm also getting the same error of PCLCrypto not found

**Comment by moljac** [comment]
@alicint @omarmallat 
Seems that dependencies for PCLCrypto have changed.
Can you provide info what versions of PCLCrypto and depending nugets are installed on blank project after adding Xamarin.Auth.

**Comment by JeffDalby** [comment]
So I'm working on getting Forms running with the new 1.5.x stuff (per my other post) and also just ran into this. Created a blank project, added Xamarin Auth 1.5.0-alpha-11 via NuGet.   While it shows a dependency of PCLCrypto >= 2.0.147, PCLCrypto was not automatically added, and when building you get the error "Could not load assembly 'PCLCrypto, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d4421c8a4786956c'. Perhaps it doesn't exist in the Mono for Android profile?"

Which makes sense given that it wasn't installed automatically. 

I added PCLCrypto 2.0.147 by hand and now it will build.

**Comment by moljac** [comment]
@JeffDalby 

This dependency was added after analysis of this issue:

https://github.com/xamarin/Xamarin.Auth/issues/129#issuecomment-265800111

How is your "Dependency behaviour" for nuget set? Not sure what is causing this.

**Comment by JeffDalby** [comment]
@moljac Yeah it's not making any sense to me, especially given that it's a 100% blank new project (does it on our main app too thought).  Dependency behavior is set to lowest, so it should be picking it up.

**Comment by moljac** [comment]
I had a lot of problems with packages too. Especially on Android after adding CustomTabs and even more with Forms.

Try adding Xamarin.Auth.XamarinForms prerelease package only. It should pull Xamarin.Auth and Xamarin.Auth should pull PCLCrypto >= 2.0.147

**Comment by JeffDalby** [comment]
OK so here's what' I've found so far- for me, in both my blank and production projects, Xamarin.Auth and Xamarin.Auth.XamarinForms will not install any dependencies for both 1.4.1 or 1.5.0.alpha-11on Android only.  It will install the right dependencies for UWP and iOS.  It will also install them when using 1.3.2.x on Android.

Did a little research and most everything I can find that is similar says it can be caused by the target  Platform and/or default configuration when creating the NuGet package.  Any chance when building the nuget packages for Android it was set to something different than 1.3.2 was set to (on Android) ?  Of course that could be totally unrelated, it's just the only thing I'm finding as a potential cause for dependencies not to work on a single platform.

**Comment by moljac** [comment]
@JeffDalby 
You see for you the problem is Android, some other people report iOS. Sorry, but didn't have much time to dive deeper into nuget problem.

Here are nuspecs for 1.5.0-alpha-11:

https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch/nuget 

If you see something suspicious let me know pls.

In -alpha-12 I'm adding *.pdb files so we'll jave *.nupkg and *.symbols.nupkg for debugging (among adding Forms Rednerers for Windows platforms)

**Comment by omarmallat** [comment]
@moljac, I have visual studio 2017, I created a new xamarin form project, (android project targetting latest nugat7,1), and I updated everything in nuget to the latest stable version. I added xamarin.firebase packages and tested successfully the messaging.
after thant, I added xamarin.auth 1.4.1, which is also the latest stable nuget package, because I want to test logging in using social.  
however, I'm getting the error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'PCLCrypto, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d4421c8a4786956c'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'PCLCrypto.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	TestApp.Android

**Comment by moljac** [comment]
@omarmallat I (we) have no idea and currently not much time to dive deeper into this Android issue.

Please read this one:
https://github.com/xamarin/Xamarin.Auth/issues/123#issuecomment-299244267

Seems that PCLCrypto must be manually added

**Comment by seancarroll** [comment]
@JeffDalby I attempted to follow the steps you provided. I'm referencing PCLCrypto 2.0.147 and Xamarin.Auth and have tried and 1.4.1 as well as 1.5.0-alpha-15 but still hit that error. Wouldn't happen to have any other advice or suggestions by chance?

**Comment by hvaughan3** [comment]
@seancarroll I would suggest try uninstalling Xamarin.Auth, install the latest version of PCLCrypto, install the 1.3.X version of Xamarin.Auth, make sure everything compiles and runs, now update Xamarin.Auth.

I say that cause I originally had the 1.3.X version running fine and was able to successfully update to 1.4.1 just fine. Have not yet tried 1.5.0.

**Comment by JeffDalby** [comment]
@seancarroll in addition to @hvaughan3 suggestion, if you haven’t yet, clean the solution and delete everything in the bin and obj directories and rebuild.  If you have PCLCrypto installed and are still getting an error that it isn't found, I would think it was an issue in the build process vs something in Xamarin Auth, maybe something going wierd with the linker?
