### ISSUE TITLE
Error building Xamarin.Forms (Android) app with Linker: CustomTabs

### ISSUE THREAD

**Issue by akamud** [xamarin/Xamarin.Auth#167]
When building an Android app made with Xamarin.Forms 2.3.4.224 and Linker enabled, we get an error related to Android Support CustomTabs:

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: 
Error: Error executing task LinkAssemblies: error XA2006: Could not resolve reference to 'Android.Support.CustomTabs.CustomTabsClient/ExtraCallbackDelegate' 
(defined in assembly 'Xamarin.Auth, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 
When the scope is different from the defining assembly, it usually means that the type is forwarded. (MyApp.Droid)
```

This does not happen when you build with linker off. I believe this is caused by a higher dependency of CustomTabs needed for Xamarin.Auth (25.1.1) than I have in my project (23.3.0). The problem is that this newer version is not compatible with any Xamarin.Forms project at the moment, because Xamarin.Forms have a hard dependency on Support Libraries, they must be *exactly* 23.3.0, and updating CustomTabs would require newer versions of the support libraries.

Does Xamarin.Auth really need a higher dependency? Can't it use an older version (>= 23.3.0) to make it more compatible with Xamarin.Forms?

Relevant packages used:
Xamarin.Auth 1.4.1.0
Xamarin.Forms 2.3.4.224
Xamarin.Android.Support.CustomTabs 23.3.0

**Comment by moljac** [comment]
@akamud 
Thanks for your report - helps a lot. I'm investigating similar errors with Forms support. Xamarin.Auth has grown so much so I cannot have every detail in my sight.
I will downgrade CustomTabs to whatever makes sense.

I'm confusued with contradictory "old" and ">=23.3.0". 
I think you mean "<=23.3.0" or am I wrong?

**Comment by akamud** [comment]
Xamarin.Forms requires "= 23.3.0" for quite some time now, so I think it makes sense supporting ">= 23.3.0" so newer versions of Xamarin.Forms can work too without you needing to change anything.

But of course, if Xamarin.Auth can work with anything lower than 23.3.0, then lower dependencies are always better ;)

**Comment by moljac** [comment]
@akamud Please try 1.5.0-alpha-03 and let me know how it works. I pinned it at 23.3.0 for a moment

**Comment by akamud** [comment]
It builds now. So >=23.3.0 should be fine for current and future Xamarin.Forms apps.

**Comment by ptedeschi** [comment]
Hi @akamud.
What exactly you did to achive build it successfully?

I am using Xamarin.Forms version "2.3.4.231" and I am getting this same error.
I tried change Xamarin.Auth to the beta versions as well as change Xamarin.Android.Support.CustomTabs version. Nothing worked yet

**Comment by akamud** [comment]
You should not change the CustomTabs version, let Xamarin.Auth download this dependency for you, since in `moljac` test he pinned it to 23.3.0.

I simply referenced Xamarin Auth beta package and everything worked.

To make sure, remove Xamarin.Auth and CustomTabs, then add just the Xamarin.Auth beta package and see if it builds.

**Comment by ptedeschi** [comment]
Thanks. It worked with 1.5.0-alpha-03. Tried with 1.5.0-alpha-09 but it failed.

**Comment by akamud** [comment]
That's weird. It should work, since it accepts CustomTabs >= 23.3.0.

Can you confirm which version of CustomTabs it installed?

**Comment by akamud** [comment]
Are you on Visual Studio? Can you confirm it works if you choose "Lowest Dependency" when installing the nuget package?

**Comment by fileman** [comment]
Hi, I have same issue on VS2017, nuget alpha-09 with lowest dependency install 23.3.0 and build fail, downgrade to alpha-08 build success.
Error:
The "LinkAssemblies" task failed unexpectedly.Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.Content.Context,Android.Net.Uri)' (defined in assembly 'Xamarin.Auth, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by akamud** [comment]
It's a different method than my original issue, but still related.

@moljac I guess we'll have to pin to = 23.3.0 then, when Xamarin.Forms updates we will need to take a look at this again. I didn't know requiring >= would still break at the moment. Sorry about that :/

**Comment by AmaralDR** [comment]
I returned to version 1.4.0 and re-generated the file

**Comment by moljac** [comment]
Fixed in 1.5.0
Closing

**Comment by DFerenczi** [comment]
Hello, I still have this issue with version 1.5.0.
Just bumped my Xamarin.Forms version to 2.3.4.247 and getting:

The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.Content.Context,Android.Net.Uri)' (defined in assembly 'Xamarin.Auth, ... " 

when I try to build in Release. Works in debug. 

Any ideas? 

/Ferenczi

**Comment by DFerenczi** [comment]
Noticed one thing that might be relevant or not, but if I tick the Use Shared Runtime checkbox I can build in release again. Problem is that I wont be able to archive with that ticked. Is this not a problem for you guys anymore?

**Comment by akamud** [comment]
Which version of `Xamarin.Android.Support.CustomTabs` do you have?

**Comment by DFerenczi** [comment]
currently on 23.3.0.

**Comment by DFerenczi** [comment]
Degraded Xamarin.Auth to 1.5.0-alpha-03 and now it works building in release?! @moljac can you see any related changes between alpha-03 and the stable version? 

/Ferenczi

**Comment by DFerenczi** [comment]
Alright so I investigated some more and the Release builds for every alpha up to 1.5.0-alpha-08 and all packages after that (including stable) failes with the error given above. Hope this encircles the problem or helps in anyway. 

/Ferenczi

**Comment by biapar** [comment]
I've the same problem!

**Comment by tura08** [comment]
Having this issue as well with 1.5.0.3. Getting the following error:

> UNHANDLED EXCEPTION: 06-30 11:40:48.903 I/MonoDroid( 7670): System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.

**Comment by biapar** [comment]
@tura08 I've a similar error like write here: https://github.com/xamarin/Xamarin.Auth/issues/201 when run in debug mode.
I've read that you need to disable linker

**Comment by tura08** [comment]
I have disabled the linker. I'm running Xamarin.Android (not Forms) in debug with no linker.

**Comment by biapar** [comment]
Other tip that I read but not tried yet:
enable "Multi-Dex" in build options

**Comment by tura08** [comment]
Will try

**Comment by biapar** [comment]
I solved the problems:
- updates to latest xamarin forms stable version
- update to latest Xamarin.Auth stable version
- update Android support libs to latest stable version

**So after every nuget install you need to clean and rebuild application.**
Configure your output buil log to show detail info: Tools/Options/Build and Run -> MSBuild project build output verbosity to “Detailed”
If you exceed max 65536  like me  enable multi dex( _Too many field references: 73121; max is 65536.1>  You may try using --multi-dex option._ ).
Follow https://przemekraciborski.eu/

In release config, I leave enabled the linker on SDK only.
If you had error INSTALL_FAILED_NO_MATCHING_ABIS check your target architecture in Android Options ->Advanced

![image](https://user-images.githubusercontent.com/661517/27760466-4e5396ba-5e48-11e7-9e55-99b07bba0ffc.png)

**Comment by tura08** [comment]
@biapar I could not get this to work with your fix. BTW, I am using Xamarin.Android not Forms. What is the code you're using to setup the Authenticator? is it something like:

```
var auth = new OAuth2Authenticator(
    ClientId,
    Scope,
    new Uri(AuthorizeUrl),
    new Uri(RedirectUrl),
    null,
    true);

    StartActivity(auth.GetUI(this));
```

**Comment by biapar** [comment]
Hi, I read that it's changed how to call the authentication for the Xamarin Android or native.

```
using Xamarin.Auth;
// ...
OAuth2Authenticator auth = new OAuth2Authenticator 
    (
        clientId: "App ID from https://developers.facebook.com/apps",
        scope: "",
        authorizeUrl: new Uri ("https://m.facebook.com/dialog/oauth/"),
        redirectUrl: new Uri ("http://www.facebook.com/connect/login_success.html"),
        // switch for new Native UI API
        //      true = Android Custom Tabs and/or iOS Safari View Controller
        //      false = Embedded Browsers used (Android WebView, iOS UIWebView)
        //  default = false  (not using NEW native UI)
        isUsingNativeUI: use_native_ui
    );
```

**Comment by BioTurboNick** [comment]
@tura08 and later: That appears to be a different issue than the one originally raised. Linker error vs. runtime exception?

**Comment by mikegottlieb** [comment]
I am also seeing this. I had to downgrade to get my project to build.

**Comment by andrew-nemtsev** [comment]
Confirm linker issues with Xamarin.Auth 1.5.0.3 + Xamarin.Android.Support.CustomTabs 23.4.0.1:

The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void Android.Support.CustomTabs.Chromium.SharedUtilities.CustomTabActivityHelper::LaunchUrlWithCustomTabsOrFallback(Android.App.Activity,Android.Support.CustomTabs.CustomTabsIntent,Android.Net.Uri,Android.Support.CustomTabs.Chromium.SharedUtilities.ICustomTabFallback)' in assembly: 'Xamarin.Auth.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.Content.Context,Android.Net.Uri)

**Comment by moljac** [comment]
@andrew-nemtsev Update your Android Support nugets!

**Comment by IngweLand** [comment]
Still have this linker issue with version 1.6.0-alpha03 and 1.6.0-alpha04.
The fix is to explicitly install Xamarin.Android.Support.CustomTabs nuget. By default, Xamarin.Auth resolved to 23.3.0 and that cased the issue. I manually installed current latest version (26.1.0.1) and the issue is gone.
