### ISSUE TITLE
KeyStore was not initialized

### ISSUE THREAD

**Issue by Vandersteen** [xamarin/Xamarin.Auth#223]
# Xamarin.Auth Issue

Recently I am getting KeyStore was not initialised exception when trying to do anything with the AccountStore (in Xamarin Forms).

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 1.5.0.3
- [ ] Forms = 2.3.4.267

### Steps to reproduce

```

class App : Application
{
       public App()
       {
               MainPage = ...;

               var accountStore = AccountStore.Create(Forms.Context);
               var account = accountStore.FindAccountsForService ("x").FirstOrDefault ();
       }
}
```

### Actual behaviour

```
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <6cd960837cc24c26bab2a0a29b597627>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <6cd960837cc24c26bab2a0a29b597627>:0 
  at Java.Security.KeyStore.Aliases () [0x0000a] in <d278c06ad5684d6882c743a94a93ebc2>:0 
  at Xamarin.Auth.AndroidAccountStore.FindAccountsForServiceAsync (System.String serviceId) [0x00011] in <347784a7d58c449896f76cefd9e360c2>:0 
  at Xamarin.Auth.AndroidAccountStore.FindAccountsForService (System.String serviceId) [0x00000] in C:\cxa\source\Xamarin.Auth.LinkSource\Evolve16.Labs\Security\CryptoUtilities.cs:19 
  --- End of managed Java.Security.KeyStoreException stack trace ---
java.security.KeyStoreException: KeyStore was not initialized
	at java.security.KeyStore.throwNotInitialized(KeyStore.java:96)
	at java.security.KeyStore.aliases(KeyStore.java:424)
```

**Comment by Vandersteen** [comment]
Seems like completely uninstalling the application and reïnstalling it solved the issue.

**Comment by bartdkmediahuis** [comment]
From time to time we face this issue as well.
Ofcourse a reinstall can not be the "solution" for this problem ?

Any tips on how to tackle this issue ?

**Comment by mikegottlieb** [comment]
I'm guessing by the lack of activity on this issue that there is no word on when a fix might be available.

**Comment by Vandersteen** [comment]
Recently I've been receiving this crash more often.

**Comment by mjfara** [comment]
I just hit this and have no idea how to resolve it, I've tried a re-install off Xamarin.Auth, same issue.
Any ideas?

**Comment by jamchengms** [comment]
We are also seeing this issue in production from our users for Save() function. Should we put a try catch, and just recreate the AccountStore if the somehow the store is uninitialized? I'm assuming this is due to inactivity and AccountStore gets uninitialized after a while.

**Comment by jamchengms** [comment]
We're seeing a high failure count for this on Android. Should we be calling AccountStore.Create() before calling any AccountStore operations? I'm seeing this crash both on .Save() and .FindAccountsForServiceAsync(). Please advise.

**Comment by mikegottlieb** [comment]
Still no response on this? FWIW its my number 1 crash and I see it when my application is launched in the background.

**Comment by jamchengms** [comment]
@mikegottlieb , I had to implement my own version of the AndroidAccountStore, change the store filename to a new one, and that resolved the issue. This will require your users to authenticate again since it will now load from the new filename.

        const string FileName = "Xamarin.Social.Accounts";

We were suspecting that the account store file is corrupted which was causing this problem. Ever since we change the filename, the issue count has decreased. Will update this if over time our users start getting this again.

Also, I'm avoiding the MigrateKeyStore in AndroidAccountStore. Instead, I'm calling LoadEmptyKeyStore. The logic inside MigrateKeyStore is problematic if you think of all the scenarios. Instead, we are deleting the account file, and loading a new empty store. This will hopefully reduce the chance of getting a corrupted account store.

**Comment by TamasRusvai** [comment]
Anyone found a workaround for this? Is it related to Xamarin.Android threading, or to something else? I also experience this bug a lot in production.

**Comment by newky2k** [comment]
this has been resolved in 1.6.0.2

**Comment by SangI762** [comment]
I could confirm, that this is not fully resolved. I getting this error sometimes with latest package. 
```
Java.Security.GeneralSecurityException: Uninitialized keystore at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) <0x7b8afaff60 + 0x000b7> in <c3e81ba778684b6bac8ed202e12c938d>:0 at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) <0x7b8afbcdf0 + 0x000b3> in
```
