### ISSUE TITLE
Can't Present Subclassed Authenticator in UWP

### ISSUE THREAD

**Issue by jjallen37** [xamarin/Xamarin.Auth#280]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 1.6.0.1
- [ ] component version = 

### Steps to reproduce

1. Create a subclass of OAuth2Authenticator, no implementation needed.
2. Use Presenters.OAuthLoginPresenter's Login(authenticator) method and run in UWP
3. Get Error - "Invalid Authenticator XamarinFormsSandbox.Auth.PkceOAuth2Authenticator"

Platform:

-	[] .NET version = 1.3
-	[] mono version = 

### Expected behaviour

Present Auth screen

### Actual behaviour

Crashes

-------
I found that this bug is caused in WebAuthenticatorPage.Events.xaml.cs page because of the way it type checks for OAuth1 and 2 Authenticators. I whipped together a potential fix for review here

`          if (null == authenticator)
            {
                authenticator = e.Parameter as OAuth1Authenticator;

                if (null == authenticator) // Not OAuth1 
                {
                    authenticator = e.Parameter as OAuth2Authenticator;

                    if (null == authenticator) // Not OAuth2 or OAuth2
                    {
                        Type type_authenticator = e.Parameter.GetType();
                        System.Diagnostics.Debug.WriteLine($"Invalid Authenticator {type_authenticator}");
                        throw new Xamarin.Auth.AuthException($"Invalid Authenticator {type_authenticator}");
                    }
                }
            }

**Comment by jjallen37** [comment]
@moljac 
That looks good to me, I've never seen that conditional syntax and I'm definitely about to start using it.

Thanks!

**Comment by NLorchy** [comment]
when I ran into this issue, I found this to be a little more concise:

```csharp
                authenticator = e.Parameter as WebRedirectAuthenticator;
                if (authenticator == null)
                {
                    System.Diagnostics.Debug.WriteLine($"Invalid Authenticator {e.Parameter?.GetType().ToString() ?? "null"}");
                    throw new Xamarin.Auth.AuthException($"Invalid Authenticator {e.Parameter?.GetType().ToString() ?? "null"}");
                }
```

**Comment by newky2k** [comment]
resolved

**Comment by sree-sundaram** [comment]
@moljac Has this issue been fixed in the current release 1.6.0.4?  I still encounter this when I subclass OAuth2Authenticator

**Comment by jamie-lord** [comment]
Yeah, this needs to be reopened as it's still an issue as of 1.6.0.4

**Comment by Spookenator** [comment]
It does work in the 1.7 Alpha 1 release

**Comment by moljac** [comment]
1.7.0.0 will be released in few hours.

Reopening. But please close it if it is solved in 1.7.0.0
